### PR TITLE
wsmgr-cwd: fix panic if no command is specified

### LINKED ISSUE #2: wsmgr-cwd panics if run without arguments
wsmgr-cwd panics when run without arguments. I was expecting to get some kind of help output.

```
wsmgr-cwd 
2022/06/16 10:04:49 workspace name = "3"
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.cwd()
	/home/haggi/go/pkg/mod/github.com/stapelberg/wsmgr-for-i3@v0.0.0-20220402161256-eeffe8583511/cmd/wsmgr-cwd/wsmgrcwd.go:63 +0x105
main.main()
	/home/haggi/go/pkg/mod/github.com/stapelberg/wsmgr-for-i3@v0.0.0-20220402161256-eeffe8583511/cmd/wsmgr-cwd/wsmgrcwd.go:71 +0x19
```

### PR DESCRIPTION
**Pull request by jpicht**
Fixes #2

### CODE REVIEW

File: cmd/wsmgr-cwd/wsmgrcwd.go [hunk 1]
```diff
@@ -58,6 +58,11 @@ func cwd() error {
 		log.Print(err)
 	}
 
+	// check if we have something to run
+	if len(os.Args[1:]) < 2 {
```
Comment (stapelberg) [inline cmd/wsmgr-cwd/wsmgrcwd.go:62]: This should be `len(os.Args[1:]) < 1`, no? `wsmgr-cwd whoami` works.

Better yet: move the `args := os.Args[1:]` line above and then work with `args`

File: cmd/wsmgr-cwd/wsmgrcwd.go [hunk 2]
```diff
@@ -58,6 +58,11 @@ func cwd() error {
...
+		log.Fatal("no command to execute")
```
Comment (stapelberg) [inline cmd/wsmgr-cwd/wsmgrcwd.go:63]: Can you make the error message print the desired syntax please? E.g. `log.Fatalf("no command to execute: syntax: %s <command>", os.Args[0])`

**Review by stapelberg — CHANGES_REQUESTED** [review]
Thanks for your PR!

File: cmd/wsmgr-cwd/wsmgrcwd.go (hunk 2 above)
Comment (jpicht) [reply cmd/wsmgr-cwd/wsmgrcwd.go]: done

**Review by stapelberg — APPROVED** [review]

File: cmd/wsmgr-cwd/wsmgrcwd.go (hunk 1 above)
Comment (jpicht) [reply cmd/wsmgr-cwd/wsmgrcwd.go]: I did not want to do that, because if somebody calls `execve(2)` wrong, `os.Args` can actually be empty. But that's pretty much moot now, with the error message now containing `os.Args[0]`.
